### ISSUE TITLE
Makefile:46: recipe for target 'serve' failed

### ISSUE THREAD

**Issue by jeena** [mozilla-services/syncserver#64] opened 2015-11-09 16:40 UTC
So I just built the project and wanted to start it, but it doesn't want to start. I'm not sure where I should look for information on how to fix that.

    ➜ jeena@jugulator syncserver (master✗) make build
    virtualenv --python=`which python2 python | head -n 1` --no-site-packages ./local
    Running virtualenv with interpreter /usr/bin/python2
    New python executable in ./local/bin/python2
    Also creating executable in ./local/bin/python
    Installing setuptools, pip...done.
    CFLAGS="-Wno-error -Wno-error=format-security" ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future ./local/bin/pip install -r requirements.txt
    You are using pip version 6.0.6, however version 7.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Collecting https://github.com/mozilla-services/mozservices/archive/e00e1b68130423ad98d0f6185655bde650443da8.zip (from -r requirements.txt (line 11))
      Downloading https://github.com/mozilla-services/mozservices/archive/e00e1b68130423ad98d0f6185655bde650443da8.zip (53kB)
        100% |################################| 57kB 433kB/s 
    Collecting https://github.com/mozilla-services/tokenserver/archive/92361b0e7b0bff996a8fff9c894c7be850d12d16.zip (from -r requirements.txt (line 12))
      Downloading https://github.com/mozilla-services/tokenserver/archive/92361b0e7b0bff996a8fff9c894c7be850d12d16.zip (383kB)
        100% |################################| 385kB 7.3MB/s 
    Collecting https://github.com/mozilla-services/server-syncstorage/archive/1.5.11.zip (from -r requirements.txt (line 13))
      Downloading https://github.com/mozilla-services/server-syncstorage/archive/1.5.11.zip (116kB)
        100% |################################| 118kB 9.7MB/s 
    Collecting cornice==0.16.2 (from -r requirements.txt (line 1))
      Using cached cornice-0.16.2.tar.gz
        /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'paster_plugins'
          warnings.warn(msg)
    Collecting gunicorn==19.1.1 (from -r requirements.txt (line 2))
      Using cached gunicorn-19.1.1-py2.py3-none-any.whl
    Collecting pyramid==1.5 (from -r requirements.txt (line 3))
      Using cached pyramid-1.5.tar.gz
    Collecting WebOb==1.4.1 (from -r requirements.txt (line 4))
      Using cached WebOb-1.4.1.tar.gz
    Collecting requests==2.7 (from -r requirements.txt (line 5))
      Using cached requests-2.7.0-py2.py3-none-any.whl
    Collecting simplejson==3.4 (from -r requirements.txt (line 6))
      Using cached simplejson-3.4.0.tar.gz
    Collecting SQLAlchemy==0.9.4 (from -r requirements.txt (line 7))
      Using cached SQLAlchemy-0.9.4.tar.gz
    Collecting unittest2==0.5.1 (from -r requirements.txt (line 8))
      Using cached unittest2-0.5.1.tar.gz
    Collecting zope.component==4.2.1 (from -r requirements.txt (line 9))
      Using cached zope.component-4.2.1.tar.gz
    Collecting configparser==3.5.0b2 (from -r requirements.txt (line 10))
      Using cached configparser-3.5.0b2.tar.gz
    Collecting konfig (from mozsvc==0.8->-r requirements.txt (line 11))
      Using cached konfig-0.9.tar.gz
    Collecting PyBrowserID (from tokenserver==1.2.14->-r requirements.txt (line 12))
      Using cached PyBrowserID-0.9.2.tar.gz
    Collecting testfixtures (from tokenserver==1.2.14->-r requirements.txt (line 12))
      Using cached testfixtures-4.4.0-py2.py3-none-any.whl
    Collecting pyramid-hawkauth (from SyncStorage==1.5.11->-r requirements.txt (line 13))
      Using cached pyramid_hawkauth-0.1.0.tar.gz
    Collecting PyMySQL (from SyncStorage==1.5.11->-r requirements.txt (line 13))
      Using cached PyMySQL-0.6.7-py2.py3-none-any.whl
    Collecting pymysql-sa (from SyncStorage==1.5.11->-r requirements.txt (line 13))
      Using cached pymysql_sa-1.0.tar.gz
    Collecting umemcache (from SyncStorage==1.5.11->-r requirements.txt (line 13))
      Using cached umemcache-1.6.3.zip
    Collecting wsgiproxy (from SyncStorage==1.5.11->-r requirements.txt (line 13))
      Using cached WSGIProxy-0.2.2.tar.gz
    Collecting webtest (from SyncStorage==1.5.11->-r requirements.txt (line 13))
      Using cached WebTest-2.0.20-py2-none-any.whl
    Requirement already satisfied (use --upgrade to upgrade): setuptools in ./local/lib/python2.7/site-packages (from pyramid==1.5->-r requirements.txt (line 3))
    Collecting repoze.lru>=0.4 (from pyramid==1.5->-r requirements.txt (line 3))
      Using cached repoze.lru-0.6.tar.gz
    Collecting zope.interface>=3.8.0 (from pyramid==1.5->-r requirements.txt (line 3))
      Using cached zope.interface-4.1.3.tar.gz
    Collecting zope.deprecation>=3.5.0 (from pyramid==1.5->-r requirements.txt (line 3))
      Using cached zope.deprecation-4.1.2.tar.gz
    Collecting venusian>=1.0a3 (from pyramid==1.5->-r requirements.txt (line 3))
      Using cached venusian-1.0.tar.gz
    Collecting translationstring>=0.4 (from pyramid==1.5->-r requirements.txt (line 3))
      Using cached translationstring-1.3-py2.py3-none-any.whl
    Collecting PasteDeploy>=1.5.0 (from pyramid==1.5->-r requirements.txt (line 3))
      Using cached PasteDeploy-1.5.2-py2.py3-none-any.whl
    Collecting zope.event (from zope.component==4.2.1->-r requirements.txt (line 9))
      Using cached zope.event-4.1.0.tar.gz
    Collecting argparse (from konfig->mozsvc==0.8->-r requirements.txt (line 11))
      Using cached argparse-1.4.0-py2.py3-none-any.whl
    Collecting hawkauthlib>=0.1 (from pyramid-hawkauth->SyncStorage==1.5.11->-r requirements.txt (line 13))
      Using cached hawkauthlib-0.1.1.tar.gz
    Collecting tokenlib (from pyramid-hawkauth->SyncStorage==1.5.11->-r requirements.txt (line 13))
      Using cached tokenlib-0.3.1.tar.gz
    Collecting Paste (from wsgiproxy->SyncStorage==1.5.11->-r requirements.txt (line 13))
      Using cached Paste-2.0.2-py2-none-any.whl
    Collecting six (from webtest->SyncStorage==1.5.11->-r requirements.txt (line 13))
      Using cached six-1.10.0-py2.py3-none-any.whl
    Collecting beautifulsoup4 (from webtest->SyncStorage==1.5.11->-r requirements.txt (line 13))
      Using cached beautifulsoup4-4.4.1-py2-none-any.whl
    Collecting waitress>=0.8.5 (from webtest->SyncStorage==1.5.11->-r requirements.txt (line 13))
      Using cached waitress-0.8.10-py2-none-any.whl
    Installing collected packages: waitress, beautifulsoup4, six, Paste, tokenlib, hawkauthlib, argparse, zope.event, PasteDeploy, translationstring, venusian, zope.deprecation, zope.interface, repoze.lru, SyncStorage, webtest, wsgiproxy, umemcache, pymysql-sa, PyMySQL, pyramid-hawkauth, tokenserver, testfixtures, PyBrowserID, mozsvc, konfig, configparser, zope.component, unittest2, SQLAlchemy, simplejson, requests, WebOb, pyramid, gunicorn, cornice

      Running setup.py install for tokenlib
      Running setup.py install for hawkauthlib

      Running setup.py install for zope.event
        Skipping installation of /home/jeena/syncserver/local/lib64/python2.7/site-packages/zope/__init__.py (namespace package)
        Installing /home/jeena/syncserver/local/lib64/python2.7/site-packages/zope.event-4.1.0-py2.7-nspkg.pth

      Running setup.py install for venusian
      Running setup.py install for zope.deprecation
        Skipping installation of /home/jeena/syncserver/local/lib64/python2.7/site-packages/zope/__init__.py (namespace package)
        Installing /home/jeena/syncserver/local/lib64/python2.7/site-packages/zope.deprecation-4.1.2-py2.7-nspkg.pth
      Running setup.py install for zope.interface
        building 'zope.interface._zope_interface_coptimizations' extension
        x86_64-pc-linux-gnu-gcc -pthread -Wno-error -Wno-error=format-security -fPIC -I/usr/include/python2.7 -c src/zope/interface/_zope_interface_coptimizations.c -o build/temp.linux-x86_64-2.7/src/zope/interface/_zope_interface_coptimizations.o
        x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -L. -Wno-error -Wno-error=format-security build/temp.linux-x86_64-2.7/src/zope/interface/_zope_interface_coptimizations.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/zope/interface/_zope_interface_coptimizations.so
        Skipping installation of /home/jeena/syncserver/local/lib64/python2.7/site-packages/zope/__init__.py (namespace package)
        Installing /home/jeena/syncserver/local/lib64/python2.7/site-packages/zope.interface-4.1.3-py2.7-nspkg.pth
      Running setup.py install for repoze.lru
        Skipping installation of /home/jeena/syncserver/local/lib64/python2.7/site-packages/repoze/__init__.py (namespace package)
        Installing /home/jeena/syncserver/local/lib64/python2.7/site-packages/repoze.lru-0.6-py2.7-nspkg.pth
      Running setup.py install for SyncStorage

      Running setup.py install for wsgiproxy
      Running setup.py install for umemcache
        building 'umemcache' extension
        x86_64-pc-linux-gnu-g++ -pthread -fPIC -DWIN32_LEAN_AND_MEAN -I./lib/ -I/usr/include/python2.7 -c ./python/umemcache.cpp -o build/temp.linux-x86_64-2.7/./python/umemcache.o
        ./python/umemcache.cpp: In function ‘int Client_init(PyClient*, PyObject*, PyObject*)’:
        ./python/umemcache.cpp:255:60: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
           static char *kwlist[] = {"address", "max_item_size", NULL};
                                                                    ^
        ./python/umemcache.cpp:255:60: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
        ./python/umemcache.cpp: In function ‘PyObject* Client_incr(PyClient*, PyObject*)’:
        ./python/umemcache.cpp:822:62: warning: format not a string literal and no format arguments [-Wformat-security]
                 return PyErr_Format(umemcache_MemcachedError, pResult);
                                                                      ^
        ./python/umemcache.cpp: In function ‘PyObject* Client_decr(PyClient*, PyObject*)’:
        ./python/umemcache.cpp:870:62: warning: format not a string literal and no format arguments [-Wformat-security]
                 return PyErr_Format(umemcache_MemcachedError, pResult);
                                                                      ^
        ./python/umemcache.cpp: At global scope:
        ./python/umemcache.cpp:1056:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
         };
         ^
        ./python/umemcache.cpp:1056:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
        ./python/umemcache.cpp:1056:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
        ./python/umemcache.cpp:1056:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
        ./python/umemcache.cpp:1056:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
        ./python/umemcache.cpp:1056:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
        ./python/umemcache.cpp:1056:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
        ./python/umemcache.cpp:1056:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
        ./python/umemcache.cpp: In function ‘void initumemcache()’:
        ./python/umemcache.cpp:1124:31: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
               PyExc_RuntimeError, NULL);
                                       ^
        x86_64-pc-linux-gnu-g++ -pthread -fPIC -DWIN32_LEAN_AND_MEAN -I./lib/ -I/usr/include/python2.7 -c ./lib/PacketReader.cpp -o build/temp.linux-x86_64-2.7/./lib/PacketReader.o
        x86_64-pc-linux-gnu-g++ -pthread -fPIC -DWIN32_LEAN_AND_MEAN -I./lib/ -I/usr/include/python2.7 -c ./lib/PacketWriter.cpp -o build/temp.linux-x86_64-2.7/./lib/PacketWriter.o
        ./lib/PacketWriter.cpp: In function ‘void PrintBuffer(FILE*, void*, size_t, int)’:
        ./lib/PacketWriter.cpp:149:56: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
           fprintf (file, "%u %p --------------\n", len, _offset);
                                                                ^
        ./lib/PacketWriter.cpp:153:33: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
             fprintf (file, "%08x: ", cnt);
                                         ^
        x86_64-pc-linux-gnu-g++ -pthread -fPIC -DWIN32_LEAN_AND_MEAN -I./lib/ -I/usr/include/python2.7 -c ./lib/Client.cpp -o build/temp.linux-x86_64-2.7/./lib/Client.o
        ./lib/Client.cpp: In member function ‘bool Client::extractErrorFromReader()’:
        ./lib/Client.cpp:554:19: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
               errorString = "malformed error received";
                           ^
        x86_64-pc-linux-gnu-g++ -pthread -shared build/temp.linux-x86_64-2.7/./python/umemcache.o build/temp.linux-x86_64-2.7/./lib/PacketReader.o build/temp.linux-x86_64-2.7/./lib/PacketWriter.o build/temp.linux-x86_64-2.7/./lib/Client.o -L/usr/lib64 -lstdc++ -lpython2.7 -o build/lib.linux-x86_64-2.7/umemcache.so
      Running setup.py install for pymysql-sa

      Running setup.py install for pyramid-hawkauth
      Running setup.py install for tokenserver

      Running setup.py install for PyBrowserID
      Running setup.py install for mozsvc
      Running setup.py install for konfig
      Running setup.py install for configparser
        Skipping installation of /home/jeena/syncserver/local/lib64/python2.7/site-packages/backports/__init__.py (namespace package)
        Installing /home/jeena/syncserver/local/lib64/python2.7/site-packages/configparser-3.5.0b2-py2.7-nspkg.pth
      Running setup.py install for zope.component
        Skipping installation of /home/jeena/syncserver/local/lib64/python2.7/site-packages/zope/__init__.py (namespace package)
        Installing /home/jeena/syncserver/local/lib64/python2.7/site-packages/zope.component-4.2.1-py2.7-nspkg.pth
      Running setup.py install for unittest2
        changing mode of build/scripts-2.7/unit2.py from 644 to 755
        changing mode of build/scripts-2.7/unit2 from 644 to 755
        changing mode of /home/jeena/syncserver/local/bin/unit2.py to 755
        changing mode of /home/jeena/syncserver/local/bin/unit2 to 755
        Installing unit2 script to /home/jeena/syncserver/local/bin
        Installing unit2-2.7 script to /home/jeena/syncserver/local/bin
      Running setup.py install for SQLAlchemy
        building 'sqlalchemy.cprocessors' extension
        x86_64-pc-linux-gnu-gcc -pthread -Wno-error -Wno-error=format-security -fPIC -I/usr/include/python2.7 -c lib/sqlalchemy/cextension/processors.c -o build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/processors.o
        x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -L. -Wno-error -Wno-error=format-security build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/processors.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/sqlalchemy/cprocessors.so
        building 'sqlalchemy.cresultproxy' extension
        x86_64-pc-linux-gnu-gcc -pthread -Wno-error -Wno-error=format-security -fPIC -I/usr/include/python2.7 -c lib/sqlalchemy/cextension/resultproxy.c -o build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/resultproxy.o
        x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -L. -Wno-error -Wno-error=format-security build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/resultproxy.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/sqlalchemy/cresultproxy.so
        building 'sqlalchemy.cutils' extension
        x86_64-pc-linux-gnu-gcc -pthread -Wno-error -Wno-error=format-security -fPIC -I/usr/include/python2.7 -c lib/sqlalchemy/cextension/utils.c -o build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/utils.o
        x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -L. -Wno-error -Wno-error=format-security build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/utils.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/sqlalchemy/cutils.so
      Running setup.py install for simplejson
        building 'simplejson._speedups' extension
        x86_64-pc-linux-gnu-gcc -pthread -Wno-error -Wno-error=format-security -fPIC -I/usr/include/python2.7 -c simplejson/_speedups.c -o build/temp.linux-x86_64-2.7/simplejson/_speedups.o
        x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -L. -Wno-error -Wno-error=format-security build/temp.linux-x86_64-2.7/simplejson/_speedups.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/simplejson/_speedups.so

      Running setup.py install for WebOb
      Running setup.py install for pyramid
        Installing ptweens script to /home/jeena/syncserver/local/bin
        Installing pdistreport script to /home/jeena/syncserver/local/bin
        Installing proutes script to /home/jeena/syncserver/local/bin
        Installing pshell script to /home/jeena/syncserver/local/bin
        Installing prequest script to /home/jeena/syncserver/local/bin
        Installing pviews script to /home/jeena/syncserver/local/bin
        Installing pcreate script to /home/jeena/syncserver/local/bin
        Installing pserve script to /home/jeena/syncserver/local/bin
      Compiling /tmp/pip-build-oc0fHV/gunicorn/gunicorn/workers/_gaiohttp.py
      

      Running setup.py install for cornice
        /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'paster_plugins'
          warnings.warn(msg)
    Successfully installed Paste-2.0.2 PasteDeploy-1.5.2 PyBrowserID-0.9.2 PyMySQL-0.6.7 SQLAlchemy-0.9.4 SyncStorage-1.5.11 WebOb-1.4.1 argparse-1.4.0 beautifulsoup4-4.4.1 configparser-3.5.0b2 cornice-0.16.2 gunicorn-19.1.1 hawkauthlib-0.1.1 konfig-0.9 mozsvc-0.8 pymysql-sa-1.0 pyramid-1.5 pyramid-hawkauth-0.1.0 repoze.lru-0.6 requests-2.7.0 simplejson-3.4.0 six-1.10.0 testfixtures-4.4.0 tokenlib-0.3.1 tokenserver-1.2.14 translationstring-1.3 umemcache-1.6.3 unittest2-0.5.1 venusian-1.0 waitress-0.8.10 webtest-2.0.20 wsgiproxy-0.2.2 zope.component-4.2.1 zope.deprecation-4.1.2 zope.event-4.1.0 zope.interface-4.1.3
    ./local/bin/python ./setup.py develop
    running develop
    running egg_info
    writing syncserver.egg-info/PKG-INFO
    writing top-level names to syncserver.egg-info/top_level.txt
    writing dependency_links to syncserver.egg-info/dependency_links.txt
    writing entry points to syncserver.egg-info/entry_points.txt
    reading manifest file 'syncserver.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'syncserver.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/jeena/syncserver/local/lib/python2.7/site-packages/syncserver.egg-link (link to .)
    Adding syncserver 1.5.2 to easy-install.pth file

    Installed /home/jeena/syncserver
    Processing dependencies for syncserver==1.5.2
    Finished processing dependencies for syncserver==1.5.2
    touch ./local/COMPLETE
    ➜ jeena@jugulator syncserver (master✗) make serve 
    ./local/bin/gunicorn --paste ./syncserver.ini
    Makefile:46: recipe for target 'serve' failed
    make: *** [serve] Error 3
    ➜ jeena@jugulator syncserver (master✗)

**Comment by rfk** [comment] 2015-11-09 21:01
Hi @jeena, hopefully we can help you debug.  What happens if you try the command by hand, like:

```
./local/bin/gunicorn --paste ./syncserver.ini
```

Does it print any extra error logs?  Does it exit with an error code?  (use `echo $?` to print the status code returned by the process when it exited).

**Comment by jeena** [comment] 2015-11-09 21:35
It doesn't print anything but the exit code is: 3

    ➜ jeena@jugulator syncserver (master✗) ./local/bin/gunicorn --paste ./syncserver.ini
    ➜ jeena@jugulator syncserver (master✗) echo $?
    3

**Comment by jeena** [comment] 2015-11-10 06:50
I just tested it and locally on my laptop with Arch Linux it seems to work without problems. But on my Gentoo server it just stops with this error 3.

**Comment by jeena** [comment] 2015-11-10 06:53
And when I want to run the tests with `make test` then I get this error:

    ImportError: No module named pysqlite2

**Comment by jeena** [comment] 2015-11-10 07:25
So I started it so it would write into a log file and the pysqlite2 seems to be the problem on that machine:

    ➜ jeena@jugulator syncserver (master) ./local/bin/gunicorn --paste ./syncserver.ini --log-file=foo.log
    ➜ jeena@jugulator syncserver (master✗) cat foo.log 
    [2015-11-10 08:23:53 +0000] [29212] [INFO] Starting gunicorn 19.1.1
    [2015-11-10 08:23:53 +0000] [29212] [INFO] Listening at: http://0.0.0.0:5000 (29212)
    [2015-11-10 08:23:53 +0000] [29212] [INFO] Using worker: sync
    [2015-11-10 08:23:53 +0000] [29217] [INFO] Booting worker with pid: 29217
    [2015-11-10 08:23:53 +0000] [29217] [ERROR] Exception in worker process:
    Traceback (most recent call last):
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
        worker.init_process()
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
        self.wsgi = self.app.wsgi()
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
        self.callable = self.load()
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 63, in load
        return self.load_pasteapp()
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
        return load_pasteapp(self.cfgurl, self.relpath, global_conf=None)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/gunicorn/app/pasterapp.py", line 73, in load_pasteapp
        global_conf=global_conf)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
        return loadobj(APP, uri, name=name, **kw)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
        return context.create()
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
        return self.object_type.invoke(self)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
        return fix_call(context.object, context.global_conf, **context.local_conf)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
        val = callable(*args, **kw)
      File "/home/jeena/syncserver/syncserver/__init__.py", line 167, in main
        config = get_configurator(global_config, **settings)
      File "/home/jeena/syncserver/syncserver/__init__.py", line 159, in get_configurator
        config.include(includeme)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
        c(configurator)
      File "/home/jeena/syncserver/syncserver/__init__.py", line 99, in includeme
        config.include("syncstorage", route_prefix="/storage")
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
        c(configurator)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/syncstorage/__init__.py", line 18, in includeme
        config.include("syncstorage.storage")
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
        c(configurator)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/syncstorage/storage/__init__.py", line 479, in includeme
        storage = load_storage_from_settings("storage", settings)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/syncstorage/storage/__init__.py", line 503, in load_storage_from_settings
        return klass(**section_settings)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/syncstorage/storage/sql/__init__.py", line 122, in __init__
        self.dbconnector = DBConnector(sqluri, **dbkwds)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/syncstorage/storage/sql/dbconnect.py", line 292, in __init__
        self.engine = create_engine(sqluri, **sqlkw)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 344, in create_engine
        return strategy.create(*args, **kwargs)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 73, in create
        dbapi = dialect_cls.dbapi(**dbapi_args)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 297, in dbapi
        raise e
    ImportError: No module named pysqlite2
    Traceback (most recent call last):
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
        worker.init_process()
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
        self.wsgi = self.app.wsgi()
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
        self.callable = self.load()
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 63, in load
        return self.load_pasteapp()
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
        return load_pasteapp(self.cfgurl, self.relpath, global_conf=None)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/gunicorn/app/pasterapp.py", line 73, in load_pasteapp
        global_conf=global_conf)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
        return loadobj(APP, uri, name=name, **kw)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
        return context.create()
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
        return self.object_type.invoke(self)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
        return fix_call(context.object, context.global_conf, **context.local_conf)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
        val = callable(*args, **kw)
      File "/home/jeena/syncserver/syncserver/__init__.py", line 167, in main
        config = get_configurator(global_config, **settings)
      File "/home/jeena/syncserver/syncserver/__init__.py", line 159, in get_configurator
        config.include(includeme)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
        c(configurator)
      File "/home/jeena/syncserver/syncserver/__init__.py", line 99, in includeme
        config.include("syncstorage", route_prefix="/storage")
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
        c(configurator)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/syncstorage/__init__.py", line 18, in includeme
        config.include("syncstorage.storage")
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 754, in include
        c(configurator)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/syncstorage/storage/__init__.py", line 479, in includeme
        storage = load_storage_from_settings("storage", settings)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/syncstorage/storage/__init__.py", line 503, in load_storage_from_settings
        return klass(**section_settings)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/syncstorage/storage/sql/__init__.py", line 122, in __init__
        self.dbconnector = DBConnector(sqluri, **dbkwds)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/syncstorage/storage/sql/dbconnect.py", line 292, in __init__
        self.engine = create_engine(sqluri, **sqlkw)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 344, in create_engine
        return strategy.create(*args, **kwargs)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 73, in create
        dbapi = dialect_cls.dbapi(**dbapi_args)
      File "/home/jeena/syncserver/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 297, in dbapi
        raise e
    ImportError: No module named pysqlite2
    [2015-11-10 08:23:53 +0000] [29217] [INFO] Worker exiting (pid: 29217)
    [2015-11-10 08:23:53 +0000] [29212] [INFO] Shutting down: Master
    [2015-11-10 08:23:53 +0000] [29212] [INFO] Reason: Worker failed to boot.

**Comment by rfk** [comment] 2015-11-10 07:31
I guess the gentoo python doesn't install sqlite by default.  In theory you can install it as a separate package with `pip install pysqlite2`, or it looks like there's a `USE` flag to enable it: 

  https://wiki.gentoo.org/wiki/Python#USE_flags

**Comment by godlike64** [comment] 2015-12-24 16:53
I believe the issue is because pysqlite2 was not installed inside the virtualenv created by make build. Simply adding pysqlite2 to requirements.txt and running make build again should make it work. I just hit the same issue when trying to start it using a postgres database backend (psycopg2 was not installed).

**Comment by rfk** [comment] 2015-12-28 08:56
Since it's related to non-standard python installs (typically sqlite is available by default) and we have discovered how to work around it, I'm going to close this issue out.  Thanks all!

**Closed by rfk** 2015-12-28 08:56 UTC

**Comment by godlike64** [comment] 2015-12-29 17:03
Well, given that the virtualenv is created by syncserver, it would be nice if we could have at least a note on the README/config file, stating that depending on the type of the chosen database backend, modifications to requirements.txt might need to be made. A plus for which modifications for which database type :)

**Comment by rfk** [comment] 2015-12-30 03:51
Fair enough :-)

I added a brief note to the readme in https://github.com/mozilla-services/syncserver/commit/570fc9d220df05d5e59c19f784773063609f2033

**Comment by godlike64** [comment] 2015-12-30 07:07
Awesome! Thanks!

**Comment by boudjelthia** [comment] 2020-06-01 04:16
hi everyone i am trying to install noxim on UNIX i have already installed the system c libraries and yaml and when i executed the instruction make it showed me this error 
Makefile:46: build/Stats.o
