### ISSUE TITLE
Invalid token leads to crash (minor issue)

### ISSUE THREAD

**Issue by zilexa** [mozilla-services/syncserver#270] opened 2021-03-15 18:50 UTC
I accidentally posted my docker-compose .env file on github, it contained my syncserver secret token. 
So I generated a new one and ran docker-compose, which recreated syncserver container. 

I was suprised to notice, all my devices still sync properly. Should I not have to log out of sync in each browser/device and login again? 

The logs only shows an issue with 1 device (for this particular account, there are 4 devices). I believe this issue should not lead to an unexpected error. But also don't understand why I don't have this error for all devices, since the token is updated, the clients should not have access anymore? 
```

172.27.0.4 - - [15/Mar/2021:18:18:21 +0000] "GET /storage/1.5/4/storage/clients?full=1&limit=1000 HTTP/1.1" 200 545 "-" "Firefox/86.0 (Windows NT 10.0; Win64; x64) FxSync/1.88.0.20210222142601.desktop"


[2021-03-15 18:18:50 +0000] [15] [DEBUG] GET /token/1.0/sync/1.5


ERROR:tokenserver:Unexpected verification error


Traceback (most recent call last):


  File "/usr/local/lib/python2.7/site-packages/tokenserver/views.py", line 171, in _valid_oauth_token


    token = verifier.verify(token)


  File "/usr/local/lib/python2.7/site-packages/tokenserver/verifiers.py", line 220, in verify


    userinfo = self._client.verify_token(token, self.scope)


  File "/usr/local/lib/python2.7/site-packages/fxa/oauth.py", line 312, in verify_token


    resp = self.apiclient.post('/verify', {'token': token})


  File "/usr/local/lib/python2.7/site-packages/fxa/_utils.py", line 338, in post


    return self.request("POST", url, json, **kwds)


  File "/usr/local/lib/python2.7/site-packages/fxa/_utils.py", line 324, in request


    raise fxa.errors.ClientError(body)


ientError: Invalid token
```

**Comment by rfk** [comment] 2021-03-16 02:50
> I was suprised to notice, all my devices still sync properly. Should I not have to log out of sync in each browser/device
> and login again?

This particular secret token is for internal use by the syncserver, to make short-lived auth tokens. The ultimate source of authentication is the long-lived auth token from your Firefox Account, which hasn't changed, so it's normal and expected that devices should continue to sync.

More concretely, the auth process for syncserver looks like this:

1. You sign in to your device with your Firefox Account, creating a long-lived "session token".
2. The device uses its session token to create a short-lived "oauth access token" signed by the FxA server.
3. The device talks to sync tokenserver to exchange the "oauth access token" for a short-lived "sync storage token"
4. The device uses the "sync storage token" to make its actual storage requests

(That's a lot of steps! They make sense in our production environment where each step is a handoff between two independent systems, but they're frankly a bit of overkill for a self-hosted setup).

The syncserver secret token is used to create the "sync storage token" at step (3). By changing the secret, you make any previously-issued sync storage tokens invalid, so the requests in step (4) would start failing. But each device can just go back to step (2) to get a fresh "oauth access token", then repeat step (3) to get a new storage token with the new secret, and continue syncing.

> ERROR:tokenserver:Unexpected verification error

I think this error is actually unrelated to the syncserver secret change. The error here is happening at step (3) above, but it's the "oauth access token" that is being reported as invalid. Probably this has triggered some edge-case in the client's retry logic and it is trying to execute step (3) without obtaining a fresh oauth access token via step (2), producing a transient error.

If the device has since recovered and continued to sync, then I don't think this is anything to worry about.

**Comment by rfk** [comment] 2021-03-16 02:50
(I'm going to close this because I think everything is working as intended, but thanks for the report!)

**Closed by rfk** 2021-03-16 02:50 UTC
